name: Build

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.6.0
        with:
          submodules: true

      - uses: actions/setup-node@v3.7.0
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

  check-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.6.0

      - uses: actions/setup-node@v3.7.0
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: dist

      - name: Check build
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

  action-tests:
    runs-on: ubuntu-latest
    needs: [check-build]

    strategy:
      matrix:
        include:
          - branch: test/test-a-affected
            workspace: test-a
            base: master
            affected: true

          - branch: test/test-a-affected
            workspace: test-a
            base: master
            pattern: '*.ts'
            affected: false

          - branch: test/test-a-affected
            workspace: test-a
            base: master
            pattern: 'src/**'
            affected: true

          - branch: test/test-a-affected
            workspace: test-b
            base: master
            affected: false

          - branch: test/tags
            workspace: test-a
            base: test-tag
            affected: true

          - branch: test/tags
            workspace: test-b
            base: test-tag
            affected: false

          - branch: test/dependency-affected
            workspace: test-c
            base: master
            affected: true

    steps:
      - uses: actions/checkout@v3.6.0

      - name: Checkout test repository
        uses: actions/checkout@v3.6.0
        with:
          repository: neoxia/test-is-workspace-affected
          path: test-repo
          ref: ${{ matrix.branch }}

      - name: Test action
        id: affected
        uses: ./
        with:
          project-root: test-repo
          workspace: ${{ matrix.workspace }}
          base: ${{ matrix.base }}
          pattern: ${{ matrix.pattern }}

      - name: Should be affected
        if: ${{ matrix.affected && !steps.affected.outputs.affected }}
        run: |
          echo "::error::Test failed: workspace ${{ matrix.workspace }} should be affected"
          exit 1

      - name: Should not be affected
        if: ${{ !matrix.affected && steps.affected.outputs.affected }}
        run: |
          echo "::error::Test failed: workspace ${{ matrix.workspace }} should not be affected"
          exit 1
